apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1 # usually 1 for a single DB instance
  selector:
    matchLabels:
      component: postgre
      app: demo-voting-app
  template:
    metadata:
      labels:
        component: postgre
        app: demo-voting-app
    spec:
      containers:
        - name: postgre
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "voting"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {} # Use PersistentVolumeClaim for real persistence
